'use strict';

// tests for create
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('create', '/handler.js', 'create');

describe('create', () => {
	before((done) => {
		done();
	});

	it('create an employee', async () => {
		const event = {
			nome: 'test',
			idade: 34,
			cargo: 'TEST',
		};

		const response = await wrapped.run(event);
		//expect(response.statusCode).to.equal(200);
		//expect(response.body).to.include(event);
	});
});
