'use strict';

// tests for getAll
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('getAll', '/handler.js', 'getAll');

describe('getAll', () => {
	before((done) => {
		done();
	});

	it('implement tests here', async () => {
		const response = await wrapped.run();
		//expect(response.body).to.be.an('array').that.is.not.empty;
		expect(response.statusCode).to.equal(200);
	});
});
